version: "3.8"

networks:
  kafka_network:
    driver: bridge

services:
  notification-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/notificationdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - kafka_network

volumes:
  postgres-data:
  redis-data:
  rabbitmq:
